CapaPresentacion/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Index()
        {
            return View();
        }
    }
}

CapaPresentacion/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;

namespace CapaPresentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EnvioMail()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListarEnvios()
        {

            List<EnvioMail> oLista = new List<EnvioMail>();

            oLista = new CN_EnvioMail().Listar();

            var jsonResult = Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }


        [HttpGet]
        public JsonResult VerMsj(int Id)
        {
            bool respuesta = false;
            

            respuesta = new CN_EnvioMail().VerMensaje(Id);


            var jsonResult = Json(new { data = respuesta }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

              return jsonResult;
        }


    }
}

CapaPresentacion/Controllers/MensajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class MensajeController : Controller
    {
        // GET: Mensaje
        public ActionResult Index()
        {
            return View();
        }
    }
}

CapaPresentacion/Views/Acceso/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                    <form action="@Url.Action("Index", "Acceso")" method="post">
                                        <div class="form-floating mb-3">
                                            <input class="form-control" name="correo" type="email" />
                                            <label for="inputEmail">Email</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" name="clave" type="password" />
                                            <label for="inputPassword">Contraseña</label>
                                        </div>

                                        @{
                                            if (ViewBag.Error != null)
                                            {
                                                <div class="form-floating mb-3">
                                                    <div class="alert alert-danger" role="alert">
                                                        @ViewBag.Error
                                                    </div>
                                                </div>
                                            }
                                        }




                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a class="small" href="@Url.Action("Reestablecer","Acceso")">¿Has olvidado tu  contraseña?</a>
                                            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
</body>
</html>

CapaPresentacion/Views/Home/EnvioMail.cshtml
@{
    ViewBag.Title = "EnvioMail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Envio De Notificaciones</li>
</ol>

<!--<div class="input-group mb-3">
    <form class="row g-3 needs-validation" novalidate>
        <div class="col-md-3">
            <label for="validationCustom04" class="form-label">Filtro</label>
            <select class="form-select" id="validationCustom04" required>
                <option selected disabled value="">Choose...</option>
                <option>...</option>
            </select>


        </div>
        <div class="col-md-3">
            <label for="validationCustom02" class="form-label">Buscar</label>
            <input type="text" class="form-control" id="validationCustom02" value="" required>
        </div>
        <div class="col-md-3">
            <label for="validationCustom04" class="form-label">En</label>
            <select class="form-select" id="validationCustom04" required>
                <option selected disabled value="">Choose...</option>
                <option>...</option>
            </select>
        </div>
        <div class="col-md-3">
            <button class="btn btn-primary btn-bloc" type="submit">Mostrar</button>
        </div>
        <div class="col-md-4">
            <label for="validationCustom03" class="form-label">Remitente</label>
            <input type="text" class="form-control" id="validationCustom03" required>


        </div>
        <div class="col-md-4">
            <label for="validationCustom03" class="form-label">Destinatario</label>
            <input type="text" class="form-control" id="validationCustom03" required>


        </div>
      

            <div class="col-md-4">
                <label for="validationCustom04" class="form-label">Categoria</label>
                <select class="form-select" id="validationCustom04" required>
                    <option selected disabled value="">Choose...</option>
                    <option>...</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="validationCustom04" class="form-label">Orden</label>
                <select class="form-select" id="validationCustom04" required>
                    <option selected disabled value="">Choose...</option>
                    <option>...</option>
                </select>
            </div>
      
    </form>-->

    @*<form id="formFecha" >
        <table>
            <tr>
                <td>
                    <input type='text' readonly id='buscar_inicio' class="datepicker form-control mt-4" placeholder='Fecha Mail' >
                </td>
                <td>
                    <input type='text' readonly id='buscar_fin' class="datepicker form-control mt-4" placeholder='Fecha fin' >
                </td>
                <td>
                    <input type='button' id="btn_search" value="Buscar" class="btn btn-primary mb-2  ">
                </td>
                <td>
                    <input type='button' id="btnLimpiar" value="Limpiar" class="btn btn-danger mb-2 ">
                </td>
            </tr>
        </table>
    </form>*@
<!--</div>-->
    <div class="card">
        <div class="card-header">

            <i class="fas fa-users me-1"></i> Envio De Mail
        </div>

        <div class="card-body">


            <table id="tabla" class="display datatable-table dt-responsive nowrap" style="width: 100%">
                <thead>

                    <tr>
                        <th>Descripcion</th>
                        <th>NombreArchivo</th>
                        <th>Motivo</th>
                        <th>Nombre y Direccion</th>
                        <th>Mensaje</th>
                        <th>Fecha de Mail</th>
                        <th>Fecha de Envio</th>



                    </tr>
                </thead>
                <tbody style="">
                </tbody>
            </table>
        </div>
    </div>


    @section scripts{

        <script>

        var tabladata;
        jQuery.ajax(
            {
                url: '@Url.Action("ListarEnvios", "Home")',
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                   console.log(data);
                }

            })

            $(document).ready(function () {

        tabladata = $("#tabla").DataTable(

            {

                //createdRow: function (row, data, dataIndex) {
                //    // Set the data-status attribute, and add a class
                //    $(row).addClass("all-row");
                //},
                ////"paging": true,
                //"dom": 'Bitp',
                //searching: true,
                searchPanes: {
                    cascadePanes: true,
                    dtOpts: {
                        dom: 'tp',
                        paging: 'true',
                        pagingType: 'simple',
                        searching: false
                    }
                },
                dom: 'Pfrtip',
                bDestroy: true,
                autoWidth: false,
                responsive: true,
                ordering: false,



              /*  "dom": "ft<'row'<'col-12 col-md-6'i><'col-12 col-md-6'<'d-flex justify-content-center justify-content-md-end'p>>>",*/
                "ajax": {
                    url: '@Url.Action("ListarEnvios", "Home")',
                    type: "GET",
                    dataType: "json"
                },
                "columns": [


                    {
                        "data": "oCategoria", "className": "cell text-center","render": function (data, type, row) {
                            // Combinar campos
                            return data.Descripcion
                        }
                    },
                    {
                        "data": "oAdjuntosMail", "className": "cell text-center","render": function (data, type, row) {
                            // Combinar campos
                            return data.NombreArchivo
                        }
                    },
                    //{
                    //    "data": null, render: function (data, type, row) {
                    //        // Combinar campos
                    //        return `${row.IdRemitente}</br>${row.CategoriaMail}</br> ${row.Asunto}</br>`
                    //    }
                    //},


                       {
                           "data": "oErrorSendMail", "className": "cell text-center", "render": function (data, type, row) {
                            // Combinar campos
                               return data.Motivo
                        }
                    },
                          {
                              "data": "oDireccionesMail", "className": "cell text-center", "width":"25%" , "render": function (data, type, row) {
                            // Combinar campos
                                  return `${data.Nombre}</br>${data.Direccion}</br>`
                        }
                    },

                    {
                        "data": "Mensaje", "className": "cell text-center ", "width": "10%", "render": function (data, type, row) {
                            // Combinar campos
                            return `<a role"button"  href="@Url.Action("Index", "Mensaje")"  target="_blank" onClick="${data.Id}" class="dropdown-item"><i class="fas fa-eye"></i> Mensaje</a>`;
                        }

                    },
                    {
                        "data": "Fecha", "name": "Fecha de Mail", "className": "cell text-center", "render": function (value) {
                            if (value === null) return "";
                            var pattern = /Date\(([^)]+)\)/; //date format from server side
                            var results = pattern.exec(value);
                            var dt = new Date(parseFloat(results[1]));
                            if (dt.getFullYear() === 9999) return ""; //Control para MaxValue
                            return ('0' + dt.getDate()).slice(-2) + "-" + ('0' + (dt.getMonth() + 1)).slice(-2) + "-" + dt.getFullYear() + " " + ('0' + dt.getHours()).slice(-2) + ":" + ('0' + dt.getMinutes()).slice(-2) + ":" + ('0' + dt.getSeconds()).slice(-2);


                        }
                    },
                    {
                        "data": "FechaEnvio", "name":"Fecha de Envio", "className": "cell text-center", "render": function (value) {
                            if (value === null) return "";
                            var pattern = /Date\(([^)]+)\)/; //date format from server side
                            var results = pattern.exec(value);
                            var dt = new Date(parseFloat(results[1]));
                            if (dt.getFullYear() === 9999) return ""; //Control para MaxValue
                            return ('0' + dt.getDate()).slice(-2) + "-" + ('0' + (dt.getMonth() + 1)).slice(-2) + "-" + dt.getFullYear() + " " + ('0' + dt.getHours()).slice(-2) + ":" + ('0' + dt.getMinutes()).slice(-2) + ":" + ('0' + dt.getSeconds()).slice(-2);


                        }
                    }


      //              {
      //                  "data": "Mensaje",
      //                  "render": function (data, type, row, meta) {

      //                      return `<a role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						//	<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-dots" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
						//		<path stroke="none" d="M0 0h24v24H0z" fill="none"/>
						//		<circle cx="5" cy="12" r="1" />
						//		<circle cx="12" cy="12" r="1" />
						//		<circle cx="19" cy="12" r="1" />
						//	</svg>
						//</a>
      //                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						//<a role"button" onClick="editModal(${row.Mensaje})" class="dropdown-item"><i class="fas fa-pen text-danger"></i> Editar</a>
						//<a role"button" onClick="createModalItems(${row.Mensaje})" class="dropdown-item"><i class="fas fa-plus text-success"></i> Agregar Item</a>
						//<div class="dropdown-divider"></div>
						//<a role"button" onClick="changeStatus(${row.Mensaje})" class="dropdown-item"><i class="fas ${row.ErrorId == 1 ? 'fa-ban text-danger' : 'fa-check text-success'}"></i> ${row.STATUS == 1 ? 'Inhabilitar' : 'Habilitar'}</a>
					 // </div>`;
      //                  }
      //              },

              /*      { "data": "Id", "name": "Adjuntos"  }*/


                    //    {
                    //        "data": null, render: function (value) {

                    //            // Combinar campos
                    //          /*  return `PersonalizarFecha(${row.Fecha})</br>PersonalizarFecha(${row.FechaEnvio})</br>`*/

                    //        }


                    //}




                ],
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json",

                        //"oPaginate": {
                        //    "sFirst": "Primero",
                        //    "sLast": "Último",
                        //    "sNext": "Siguiente",
                        //    "sPrevious": "Anterior"
                        //},



                }


            });
                //$('#tabla thead tr').clone(true).appendTo('#tabla thead');
                //$('#tabla thead tr:eq(1) th').each(function (i) {
                //    var title = $(this).text(); //es el nombre de la columna
                //    $(this).html('<input class="" style="width: 100%" type="text" ' + title + '" />');

                //    $('input', this).on('keyup change', function () {
                //        if (tabladata.column(i).search() !== this.value) {
                //            tabladata
                //                .column(i)
                //                .search(this.value)
                //                .draw();
                //        }
                //    });
                //});


            });


         
        </script>



    }

CapaPresentacion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CapaPresentacion/Views/Mensaje/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Mensaje</li>
</ol>


<div class="card">
    <div class="card-header">

        <i class="fas fa-users me-1"></i> Mensaje
    </div>

    <div class="card-body">


        <table id="tabla_Mensaje" class="display datatable-table dt-responsive nowrap" style="width: 100%">
            <thead>

                <tr>
             
                    <th>Mensaje</th>
                 



                </tr>
            </thead>
            <tbody style="">
            </tbody>
        </table>
    </div>
</div>


@section scripts{

    <script>

        var tabladata;
        jQuery.ajax(
            {
                url: '@Url.Action("VerMensaje", "Mensaje")',
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                   console.log(data);
                }

            })

            $(document).ready(function () {

                tabladata = $("#tabla_Mensaje").DataTable(

            {

              
              
                bDestroy: true,
                autoWidth: false,
                responsive: true,
                ordering: false,



           
                "ajax": {
                    url: '@Url.Action("VerMensaje", "Home")',
                    type: "GET",
                    dataType: "json"
                },
                "columns": [


                  
                    {
                        "data": "Mensaje", "className": "cell text-center responsive nowrap", "width": "100%", "render": function (data, type, row) {
                           
                            return row.Mensaje
                        }

                    }
                  


                ],
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json",

                  

                }


            });
               


            });


    </script>



}

CapaPresentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")

</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Envio De Notificaciones</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto  ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo de Usuario</a></li>

                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        @*<div class="sb-sidenav-menu-heading">Interface</div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
            Envio de Mail
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
            </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Envio de Whassapt
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                  Envio de Sms
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="login.html">Login</a>
                        <a class="nav-link" href="register.html">Register</a>
                        <a class="nav-link" href="password.html">Forgot Password</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                    Error
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="401.html">401 Page</a>
                        <a class="nav-link" href="404.html">404 Page</a>
                        <a class="nav-link" href="500.html">500 Page</a>
                    </nav>
                </div>
            </nav>
        </div>*@
                        <div class="sb-sidenav-menu-heading">Solicitudes de Envio</div>
                        <a class="nav-link" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fa fa-envelope"></i></div>
                            Envio de Mail
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Destinatarios</a>
                                <a class="nav-link"  href="@Url.Action("EnvioMail","Home")">Consultas</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fab fa-whatsapp"></i></div>
                            Envio de Whatsapp
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-sms"></i></div>
                            Envio de Sms
                        </a>
                    </div>
                </div>
             
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>

                @*CONTAINER*@
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>